# Generated by Django 5.2 on 2025-06-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artcals',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='artcal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artcal', to='app2.artcals'),
        ),
    ]
