# Generated by Django 5.2 on 2025-06-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_artcals_options_alter_image_artcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='artcal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app2.artcals'),
        ),
    ]
