# Generated by Django 5.2 on 2025-06-06 00:00

import django.utils.timezone
import image_pdf_crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('info', models.FileField(blank=True, null=True, upload_to=image_pdf_crud.models.get_file_path)),
                ('dec', models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel assumenda ad nemo laudantium. Rem modi vitae adipisci magnam mollitia quos, maiores sit facere tempore dignissimos hic eaque, nesciunt voluptatibus. Facere.', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.IntegerField(default=0)),
            ],
        ),
    ]
