# Generated by Django 5.2 on 2025-06-05 13:19

import app5.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('folder_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.FileField(upload_to=app5.models.content_file_name)),
                ('albumname', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('size', models.IntegerField(blank=True, null=models.IntegerField())),
                ('artcal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app5.post')),
            ],
        ),
    ]
